version: '3.4'

services:
  examplebasics:
    image: examplebasics
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4321:4321
